### ISSUE TITLE
Document Deploy branch and DataMade hosting

### ISSUE THREAD

**Issue by shua123** [chihacknight/chihacknight.org#108]
At some point this site switched from being deployed on github-pages to using a Deploy branch and being hosted by DataMade. It would be great to have documentation around how that branch and process operates. It would also be nice to have some documentation on the decision making process and reasons for switching from the chihacknight group github hosting to DataMade hosting.

**Comment by derekeder** [comment]
@shua123 thanks for bringing this up. Meant to write this up a while ago, but forgot.

ChiHackNight.org is now hosted by DataMade on an AWS server. This change happened on [April 21, 2016](https://github.com/chihacknight/chihacknight.org/commit/558cd96cc4267f3cf699e13424938ae1675baae8).

### Rationale

1. **Uptime:** Over the past year, GitHub Pages has experienced some noticeable downtime, which we have no control over. 
1. **Software upgrades:** GitHub [upgraded the Jekyll version](https://github.com/blog/2100-github-pages-now-faster-and-simpler-with-jekyll-3-0) (they only support one version of Jekyll for all GitHub Pages), which caused some unintended settings changes on our site. The result was the upcoming event stopped showing up entirely. We [implemented a fix for this upgrade here](https://github.com/chihacknight/chihacknight.org/commit/c3e6ec12482541a8ae001057035b6f272056c9b6), but future mandatory upgrades will happen on GitHub Pages.
1. **HTTPS:** With services like [Lets Encrypt](http://letsencrypt.org/), enabling HTTPS is something that no longer costs money to do. Making ChiHackNight.org HTTPS is [worthwhile for a number of reasons](https://www.bitballoon.com/blog/2014/10/03/five-reasons-you-want-https-for-your-static-site), primarily for protecting our users, our content, and the professional impression of our site and group. GitHub Pages [does not support HTTPS for custom domains](https://github.com/isaacs/github/issues/156).

### How it works

@evz set up a [deploy hook](https://developer.github.com/guides/delivering-deployments/) infrastructure with GitHub for static sites. Now, instead of pushing to `gh-pages` to deploy, we created a new branch called `deploy` that does the same thing.

For example, you can deploy the latest changes (provided you have push access) by pushing to origin (GitHub) the master branch into deploy  

```
git push origin master:deploy
```

This will trigger the deploy hook and an automatic build on the static server. Bonus! It's faster than GitHub Pages due to much lower usage (they are doing [~20k page builds / day](https://github.com/blog/1992-eight-lessons-learned-hacking-on-github-pages-for-six-months)) 😄
